# Generated by Django 4.1.4 on 2023-06-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0012_uploadedfile_name_uploadedfile_type'),
    ]

    operations = [
        
    ]
