# Generated by Django 4.1.4 on 2024-05-26 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('config', '0002_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('sheba_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('sheba_message', models.TextField(blank=True, default=None, null=True)),
                ('phone_message', models.TextField(blank=True, default=None, null=True)),
                ('is_sheba_valid', models.BooleanField(blank=True, default=False)),
                ('is_phone_valid', models.BooleanField(blank=True, default=False)),
                ('is_valid', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.config')),
            ],
        ),
    ]
