# Generated by Django 4.1.4 on 2024-05-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_authenticationvalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationvalidationlog',
            name='birth_date',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authenticationvalidationlog',
            name='national_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authenticationvalidationlog',
            name='sheba_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
