# Generated by Django 4.1.4 on 2024-06-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0072_answer_latitude_answer_longitude'),
        ('survey', '0023_surveyanswer_latitude_surveyanswer_longitude'),
        ('config', '0004_authenticationvalidationlog_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authenticationvalidationlog',
            name='is_main',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='authenticationvalidationlog',
            name='is_new',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='authenticationvalidationlog',
            name='survey_fillout',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyfillout'),
        ),
        migrations.AddField(
            model_name='authenticationvalidationlog',
            name='visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
        migrations.AlterField(
            model_name='authenticationvalidationlog',
            name='national_id',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
    ]
