# Generated by Django 4.1.4 on 2024-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_authenticationvalidationlog_is_main_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=24)),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('app_model_name', models.CharField(blank=True, default=None, max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AuthenticationValidationLog',
        ),
    ]
