# Generated by Django 4.1.4 on 2024-06-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_addin_delete_authenticationvalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='addin',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
