# Generated by Django 4.1.4 on 2025-01-09 10:52

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_merge_20241103_1156'),
        ('config', '0007_addin_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title_fa', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('image_1', models.TextField(blank=True, default=None, null=True)),
                ('image_1_alter', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('image_1_thumbnail', models.TextField(blank=True, default=None, null=True)),
                ('image_2', models.TextField(blank=True, default=None, null=True)),
                ('image_2_alter', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('image_2_thumbnail', models.TextField(blank=True, default=None, null=True)),
                ('client', models.IntegerField(blank=True, choices=[(1, 'Pwa'), (2, 'Landing')], default=None, null=True)),
                ('type', models.CharField(blank=True, choices=[('story', 'Story'), ('banner', 'Banner'), ('guider', 'Guider'), ('other', 'Other')], default=None, max_length=10, null=True)),
                ('redirect_url', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('page_url', models.TextField(blank=True, default=None, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('body_copy', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('verbose', models.CharField(blank=True, default=None, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TagManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('icon', models.TextField(default=None, null=True)),
                ('icon_thumbnail', models.TextField(default=None, null=True)),
                ('image', models.TextField(default=None, null=True)),
                ('image_thumbnail', models.TextField(default=None, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('is_visible', models.BooleanField(blank=True, default=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('datetime_last_change', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.tagtype')),
            ],
        ),
        migrations.CreateModel(
            name='NavMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('title_fa', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('active_icon', models.TextField(blank=True, default=None, null=True)),
                ('active_icon_thumbnail', models.TextField(blank=True, default=None, null=True)),
                ('deactive_icon', models.TextField(blank=True, default=None, null=True)),
                ('deactive_icon_thumbnail', models.TextField(blank=True, default=None, null=True)),
                ('priority', models.IntegerField(blank=True, default=None, null=True)),
                ('is_landing', models.BooleanField(default=False)),
                ('route', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.role')),
            ],
        ),
        # migrations.AddIndex(
        #     model_name='tagmanager',
        #     index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='config_tagm_title_ef6aee_gin'),
        # ),
        # migrations.AddIndex(
        #     model_name='tagmanager',
        #     index=django.contrib.postgres.indexes.GinIndex(fields=['title_fa'], name='config_tagm_title_f_fb3ae2_gin'),
        # ),
    ]
