# Generated by Django 4.1.4 on 2025-01-09 11:09

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_mediamanager_mediatype_tagtype_tagmanager_navmenu_and_more'),
    ]

    operations = [
        django.contrib.postgres.operations.TrigramExtension(),
        migrations.AddIndex(
            model_name='tagmanager',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='config_tagm_title_ef6aee_gin', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='tagmanager',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title_fa'], name='config_tagm_title_f_fb3ae2_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
