# Generated by Django 4.1.4 on 2025-02-25 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_tagmanager_config_tagm_title_ef6aee_gin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediamanager',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.mediatype'),
        ),
    ]
