"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import datetime, timedelta
import os
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(str(BASE_DIR) + '/.env')

# Getting Env
SERVICE_NAME = os.environ.get('SERVICE_NAME', "core_service")
environment = os.environ.get('Environment', 'LOCAL')
dev = False
test = False
production = False
local = False
if environment == "LOCAL":
    PRODUCTION = False
    local = True
elif environment == "DEV":
    PRODUCTION = False
    dev = True
elif environment == "TEST":
    PRODUCTION = False
    test = True
elif environment == "PROD":
    PRODUCTION = True
    production = True
else:
    PRODUCTION = False


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or (
    None if production else 'saan-local-development-only-change-for-deployment'
)
if not SECRET_KEY:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY must be set for production.')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not production and os.environ.get('DJANGO_DEBUG', 'true').lower() in ('1', 'true', 'yes')

_default_hosts = ('api.saanapp.ir,tapi.saanapp.ir,t.saanapp.ir,app.saanapp.ir,'
                  'admin.saanapp.ir,localhost,127.0.0.1') if production else 'localhost,127.0.0.1,testserver,api'
ALLOWED_HOSTS = [host.strip() for host in os.environ.get('DJANGO_ALLOWED_HOSTS', _default_hosts).split(',') if host.strip()]

CSRF_TRUSTED_ORIGINS = ['https://*.saanapp.ir'] if production else ['http://localhost:18120', 'http://localhost:18122']
SESSION_COOKIE_SECURE = production
CSRF_COOKIE_SECURE = production

if production:
    CORS_ALLOWED_ORIGINS = [
    "https://app.saanapp.ir",
    "https://admin.saanapp.ir",
    "https://saanapp.ir",
    "https://tapp.saanapp.ir",
    "https://tadmin.saanapp.ir",
    "https://t.saanapp.ir",
]
else:
    CORS_ALLOW_ALL_ORIGINS =True
    
    # string = os.environ.get('CORS_URLS')
    # CORS_ALLOWED_ORIGINS = string.split(';')

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
    "POKE",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "accept-language",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    'core-client',
]

# Application definition
PROJECT_APPS = [
    'auth_app',
    'visit',
    'report',
    'survey',
    'config',
    'warehouse',
    'url_utility',
    'utils',
    'wallet',
    'notification',
    'main',
    
]

DJANGO_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "corsheaders",
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_yasg',
]

INSTALLED_APPS = DJANGO_APPS + PROJECT_APPS

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    # for rate limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '800/min',
        "user": "800/min",
        'otp_request': '5/min',
        'otp_verify': '20/min',
    },

}

SIMPLE_JWT = {
        'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
        'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
        'ROTATE_REFRESH_TOKENS': True,
        'BLACKLIST_AFTER_ROTATION': True,
    }

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'core.elk.ElasticLogMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [os.path.join(BASE_DIR, 'templates/'),],
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASE_ENGINE = os.environ.get('DATABASE_ENGINE')
DATABASE_NAME = os.environ.get('DATABASE_NAME')
DATABASE_USERNAME = os.environ.get('DATABASE_USERNAME')
DATABASE_PASSWORD = os.environ.get('DATABASE_PASSWORD')
DATABASE_HOST = os.environ.get('DATABASE_HOST')
DATABASE_PORT = os.environ.get('DATABASE_PORT')


if local:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
elif DATABASE_ENGINE == 'postgresql_psycopg2':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DATABASE_NAME,
            'USER': DATABASE_USERNAME,
            'PASSWORD': DATABASE_PASSWORD,
            'HOST': DATABASE_HOST,
            'PORT': DATABASE_PORT,
        }
    }

else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# if not environment == 'LOCAL' and not environment == 'DEV':
#     # Min IO
DEFAULT_FILE_STORAGE = "minio_storage.storage.MinioMediaStorage"
STATICFILES_STORAGE = "minio_storage.storage.MinioStaticStorage"
MINIO_STORAGE_ENDPOINT = os.environ.get('STORAGE_ADDRESS', 'storage.carpiece.cp') + ":" + os.environ.get('STORAGE_PORT', '9000')
MINIO_STORAGE_ACCESS_KEY = os.environ.get('STORAGE_USER', None)
MINIO_STORAGE_SECRET_KEY = os.environ.get('STORAGE_PASSWORD', None)
MINIO_STORAGE_USE_HTTPS = False
# MINIO_STORAGE_MEDIA_BUCKET_NAME = os.environ.get('STORAGE_BUCKET', None)
MINIO_STORAGE_STATIC_BUCKET_NAME = os.environ.get('STORAGE_BUCKET', None)
MINIO_STORAGE_AUTO_CREATE_MEDIA_BUCKET = False
MINIO_STORAGE_AUTO_CREATE_STATIC_BUCKET = False
MINIO_STORAGE_STATIC_URL = os.environ.get('STORAGE_PUBLIC_ADDRESS', None) + '/' + MINIO_STORAGE_STATIC_BUCKET_NAME
# MINIO_STORAGE_MEDIA_URL = os.environ.get('STORAGE_PUBLIC_ADDRESS', None) + '/' + MINIO_STORAGE_MEDIA_BUCKET_NAME



# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
if production or test:
    STATIC_ROOT = '/home/static'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
