# Generated by Django 4.1.4 on 2023-10-23 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0066_phototype_visit_type_questiontype_visit_type_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WareType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('icon', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ware',
            name='is_for_use',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='WareVisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visittype')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.ware')),
            ],
        ),
        migrations.AddField(
            model_name='ware',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.waretype'),
        ),
    ]
