# Generated by Django 4.1.4 on 2023-10-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_waretype_ware_is_for_use_warevisittype_ware_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousetransaction',
            name='project',
        ),
    ]
