# Generated by Django 4.1.4 on 2023-10-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_warehousetransaction_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehousetransactionline',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehousetransaction'),
        ),
    ]
