# Generated by Django 4.1.4 on 2023-10-31 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_warehousetransactionline_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_en', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('unit_fa', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('unit_abbreviation', models.CharField(blank=True, default=None, max_length=12, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ware',
            name='unit_abbreviation',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='unit_en',
        ),
        migrations.RemoveField(
            model_name='ware',
            name='unit_fa',
        ),
        migrations.AddField(
            model_name='ware',
            name='unit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='warehouse.unit'),
        ),
    ]
