# Generated by Django 4.1.4 on 2024-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_unit_remove_ware_unit_abbreviation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
