# Generated by Django 4.1.4 on 2024-05-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_ware_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ware',
            name='active',
        ),
        migrations.AddField(
            model_name='ware',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
