# Generated by Django 4.1.4 on 2024-05-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_remove_ware_active_ware_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ware',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
