# Generated by Django 4.1.4 on 2024-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_alter_ware_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
