# Generated by Django 4.1.4 on 2025-02-25 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0076_visit_expert_alter_visit_promoter'),
        ('warehouse', '0009_ware_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='warevisittype',
            name='visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
        migrations.AlterField(
            model_name='warevisittype',
            name='visit_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visittype'),
        ),
        migrations.CreateModel(
            name='WarehouseLocationPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouselocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
