# Generated by Django 4.1.4 on 2026-10-01 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Count, Min, Max


def backfill_transaction_project(apps, schema_editor):
    Transaction = apps.get_model('warehouse', 'WarehouseTransaction')
    Line = apps.get_model('warehouse', 'WarehouseTransactionLine')
    pending = []
    summaries = Line.objects.using(schema_editor.connection.alias).values('transaction_id').annotate(
        first_project=Min('ware__project_id'), last_project=Max('ware__project_id'),
        line_count=Count('id'), project_count=Count('ware__project_id'),
    )
    for item in summaries.iterator(chunk_size=2000):
        if (item['first_project'] is None or item['first_project'] != item['last_project']
                or item['line_count'] != item['project_count']):
            raise RuntimeError('Warehouse transaction has missing or mixed project wares: '
                               + str(item['transaction_id']))
        pending.append(Transaction(pk=item['transaction_id'], project_id=item['first_project']))
        if len(pending) >= 500:
            Transaction.objects.using(schema_editor.connection.alias).bulk_update(pending, ['project'])
            pending.clear()
    if pending:
        Transaction.objects.using(schema_editor.connection.alias).bulk_update(pending, ['project'])


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0039_otp_consumed_at_otp_failed_attempts_alter_otp_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0010_warevisittype_visit_alter_warevisittype_visit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransaction',
            name='payload_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='warehousetransaction',
            name='request_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_transaction_project, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='warehousetransaction',
            name='creator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehousetransactionline',
            name='location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation'),
        ),
        migrations.AlterField(
            model_name='warehousetransactionline',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousetransaction'),
        ),
        migrations.AlterField(
            model_name='warehousetransactionline',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.transactionlinetype'),
        ),
        migrations.AlterField(
            model_name='warehousetransactionline',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warehousetransactionline',
            name='ware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ware'),
        ),
        migrations.AddConstraint(
            model_name='warehousetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('request_key__isnull', False)), fields=('project', 'creator', 'request_key'), name='warehouse_transfer_user_key_unique'),
        ),
    ]
