# Generated by Django 4.1.4 on 2026-10-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0012_warehousetransaction_repair_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='ware',
            name='creation_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='ware',
            name='creation_key',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='ware',
            constraint=models.UniqueConstraint(condition=models.Q(('creation_key__isnull', False)), fields=('project', 'creation_key'), name='warehouse_ware_project_creation_key_unique'),
        ),
    ]
