# Generated by Django 4.1.4 on 2026-10-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0013_ware_creation_hash_ware_creation_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousetransaction',
            name='movement_kind',
            field=models.CharField(choices=[('LEGACY', 'LEGACY'), ('RECEIPT', 'RECEIPT'), ('OPENING', 'OPENING'), ('TRANSFER', 'TRANSFER'), ('RETURN', 'RETURN'), ('CONSUME', 'CONSUME'), ('SCRAP', 'SCRAP')], default='LEGACY', max_length=12),
        ),
    ]
