# Generated by Django 4.1.4 on 2026-10-02 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0044_priority_grants'),
        ('visit', '0099_field_operations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0014_movement_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('FULFILLED', 'تحویل شد'), ('REJECTED', 'رد شد'), ('CANCELED', 'لغو شد')], default='PENDING', max_length=10)),
                ('decision_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouselocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to='auth_app.project')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to=settings.AUTH_USER_MODEL)),
                ('stock_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehousetransaction')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to='visit.visit')),
                ('ware', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_requests', to='warehouse.ware')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
    ]
