# Generated by Django 4.1.4 on 2022-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='datetime_requested',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('C', 'Customer'), ('P', 'Promoter'), ('S', 'Support')], default='P', max_length=1),
        ),
    ]
