# Generated by Django 4.1.4 on 2022-12-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_otp_datetime_requested_alter_extendeduser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
