# Generated by Django 4.1.4 on 2023-05-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_role_roleassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.BigIntegerField(blank=True, default=None, null=True)),
                ('max_value', models.BigIntegerField(blank=True, default=None, null=True)),
                ('min_lenght', models.IntegerField(blank=True, default=None, null=True)),
                ('max_lenght', models.IntegerField(blank=True, default=None, null=True)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
                ('regex', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('error_msg_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
    ]
