# Generated by Django 4.1.4 on 2023-05-04 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_survey_survey_questions_surveyquestion_survey_and_more'),
        ('auth_app', '0005_validation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Validation',
            new_name='FieldValidation',
        ),
    ]
