# Generated by Django 4.1.4 on 2023-05-16 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0006_rename_validation_fieldvalidation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('key', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('logo', models.TextField(blank=True, default=None, null=True)),
                ('image', models.TextField(blank=True, default=None, null=True)),
                ('primary_color', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('secondary_color', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('datetime_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_last_change', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor_Promoter', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Supervisor_Supervisor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdminMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_submenu', models.BooleanField(blank=True, default=False)),
                ('priority', models.IntegerField()),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('active_icon', models.TextField(blank=True, default=None, null=True)),
                ('deactive_icon', models.TextField(blank=True, default=None, null=True)),
                ('has_iframe', models.BooleanField(blank=True, default=False)),
                ('iframe_link', models.TextField(blank=True, default=None, null=True)),
                ('frontend_route_name', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('frontend_route_url', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('frontend_api_queryparams', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('frontend_route_params', models.JSONField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_menu', to='auth_app.adminmenu')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.role')),
            ],
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.CreateModel(
            name='ActiveCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.city')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
            ],
            options={
                'unique_together': {('city', 'project')},
            },
        ),
    ]
