# Generated by Django 4.1.4 on 2023-05-27 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_project_supervisor_adminmenu_roleassignment_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldvalidation',
            old_name='error_msg_en',
            new_name='lenght_error_msg_en',
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='lenght_error_msg_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='mandatory_error_msg_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='mandatory_error_msg_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='regex_error_msg_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='regex_error_msg_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='value_error_msg_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='value_error_msg_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminmenu',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_menu', to='auth_app.adminmenu'),
        ),
    ]
