# Generated by Django 4.1.4 on 2023-05-28 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_surveyphototype_survey'),
        ('visit', '0051_rename_pakshoma_code_outlet_customer_code_and_more'),
        ('auth_app', '0008_rename_error_msg_en_fieldvalidation_lenght_error_msg_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAnswerTypeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_for', models.CharField(blank=True, choices=[('V', 'For Visit App'), ('S', 'For Survey App')], default='V', max_length=1)),
                ('answer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.answertype')),
                ('survey_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
                ('validation', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.fieldvalidation')),
                ('visit_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.question')),
            ],
        ),
    ]
