# Generated by Django 4.1.4 on 2023-06-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_questionanswertypevalidation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='choice_count_error_msg_en',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='choice_count_error_msg_fa',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='max_choice_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='fieldvalidation',
            name='min_choice_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
