# Generated by Django 4.1.4 on 2023-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_uploadedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(blank=True, choices=[('EDU', 'Education')], default=None, max_length=3, null=True),
        ),
    ]
