# Generated by Django 4.1.4 on 2023-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_uploadedfile_name_uploadedfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='icon',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='type',
            field=models.CharField(blank=True, choices=[('EDU', 'Education'), ('ETC', 'Etc.')], default=None, max_length=3, null=True),
        ),
    ]
