# Generated by Django 4.1.4 on 2023-06-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_uploadedfile_icon_alter_uploadedfile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
