# Generated by Django 4.1.4 on 2023-06-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_fieldvalidation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalidation',
            name='regex',
            field=models.TextField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
