# Generated by Django 4.1.4 on 2023-06-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0015_alter_fieldvalidation_regex'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldvalidation',
            name='regex_json',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
