# Generated by Django 4.1.4 on 2023-06-27 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0016_fieldvalidation_regex_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldvalidation',
            name='regex_json',
        ),
        migrations.AlterField(
            model_name='fieldvalidation',
            name='regex',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
