# Generated by Django 4.1.4 on 2023-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0019_alter_authenticationimage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='promoting_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
