# Generated by Django 4.1.4 on 2023-09-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0020_project_promoting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
