# Generated by Django 4.1.4 on 2023-10-21 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0021_role_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abbreviation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('logo', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.company'),
        ),
    ]
