# Generated by Django 4.1.4 on 2024-02-04 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0023_region_district'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='supervisor',
            unique_together={('supervisor', 'promoter', 'project')},
        ),
        migrations.CreateModel(
            name='SupervisorChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.BooleanField(blank=True, default=False)),
                ('is_active_set_to', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('supervisor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.supervisor')),
            ],
        ),
    ]
