# Generated by Django 4.1.4 on 2024-03-05 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0024_alter_supervisor_unique_together_supervisorchangelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abbrev', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('is_requested', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='IBAN',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='birthـcertificateـnumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='شماره شناسنامه'),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='datetime_last_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'male')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='extendeduser',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='DocumentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_change', models.DateTimeField(auto_now=True, null=True)),
                ('supervisor_confirm', models.CharField(blank=True, choices=[('NOT_CHECKED', 'NOT_CHECKED'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='NOT_CHECKED', max_length=12)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_checked', models.BooleanField(blank=True, default=False)),
                ('confirm_status', models.CharField(blank=True, choices=[('NOT_CHECKED', 'NOT_CHECKED'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='NOT_CHECKED', max_length=12)),
                ('document', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
