# Generated by Django 4.1.4 on 2024-03-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0025_document_extendeduser_iban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentphoto',
            name='link',
        ),
        migrations.AddField(
            model_name='documentphoto',
            name='file',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
