# Generated by Django 4.1.4 on 2024-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0026_remove_documentphoto_link_documentphoto_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name=''),
        ),
    ]
