# Generated by Django 4.1.4 on 2024-03-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0027_extendeduser_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='abbrev',
            new_name='abbreviation',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='is_requested',
            new_name='is_mandatory',
        ),
        migrations.RenameField(
            model_name='extendeduser',
            old_name='IBAN',
            new_name='iban',
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='gender',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='extendeduser',
            name='status',
            field=models.CharField(blank=True, choices=[('F_N_C', 'Form not completed'), ('F_C', 'Form completed'), ('R', 'User is ready to assign')], default='R', max_length=20, null=True),
        ),
    ]
