# Generated by Django 4.1.4 on 2024-04-18 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0028_rename_abbrev_document_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Limiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('field_name', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create', models.BooleanField(blank=True, default=False)),
                ('can_update', models.BooleanField(blank=True, default=False)),
                ('can_delete', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_change', models.DateTimeField(auto_now=True, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.role')),
            ],
        ),
        migrations.CreateModel(
            name='ViewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255, verbose_name='view name')),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default=None, max_length=10, null=True, verbose_name='method name')),
            ],
        ),
        migrations.CreateModel(
            name='RoleViewModelField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_update', models.BooleanField(blank=True, default=False)),
                ('datetime_last_change', models.DateTimeField(auto_now=True, null=True)),
                ('model_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.modelfield')),
                ('role_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.roleview')),
            ],
        ),
        migrations.AddField(
            model_name='roleview',
            name='view_method_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.viewmethod'),
        ),
    ]
