# Generated by Django 4.1.4 on 2024-05-25 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0028_rename_abbrev_document_abbreviation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheba_message', models.TextField(blank=True, default=None, null=True)),
                ('phone_message', models.TextField(blank=True, default=None, null=True)),
                ('input_data', models.TextField(blank=True, default=None, null=True)),
                ('response', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_sheba_valid', models.BooleanField(blank=True, default=False)),
                ('is_phone_valid', models.BooleanField(blank=True, default=False)),
                ('is_valid', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
