# Generated by Django 4.1.4 on 2024-04-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_limiter_modelfield_roleview_viewmethod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmethod',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS')], default=None, max_length=10, null=True, verbose_name='method name'),
        ),
    ]
