# Generated by Django 4.1.4 on 2024-05-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0029_authenticationvalidationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthenticationValidationLog',
        ),
    ]
