# Generated by Django 4.1.4 on 2024-04-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_alter_viewmethod_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleview',
            name='is_active',
        ),
        migrations.CreateModel(
            name='RoleViewLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_change', models.DateTimeField(auto_now=True, null=True)),
                ('limiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.limiter')),
                ('role_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.roleview')),
            ],
        ),
    ]
