# Generated by Django 4.1.4 on 2024-05-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0030_delete_authenticationvalidationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='priority',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
