# Generated by Django 4.1.4 on 2024-04-20 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0031_remove_roleview_is_active_roleviewlimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewmethod',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('PATCH', 'PATCH')], default=None, max_length=10, null=True, verbose_name='method name'),
        ),
        migrations.CreateModel(
            name='LogLimiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('model', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('view_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_get', models.BooleanField(blank=True, default=False)),
                ('is_put', models.BooleanField(blank=True, default=False)),
                ('is_patch', models.BooleanField(blank=True, default=False)),
                ('is_options', models.BooleanField(blank=True, default=False)),
                ('is_delete', models.BooleanField(blank=True, default=False)),
                ('is_post', models.BooleanField(blank=True, default=False)),
                ('is_solved', models.BooleanField(blank=True, default=False)),
                ('user', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('project', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('datetime_last_change', models.DateTimeField(auto_now=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('role_view_limiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.roleviewlimiter')),
            ],
        ),
    ]
