# Generated by Django 4.1.4 on 2024-06-11 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_survey_add_ins'),
        ('visit', '0072_answer_latitude_answer_longitude'),
        ('config', '0006_addin_delete_authenticationvalidationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0031_uploadedfile_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticationValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('sheba_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('sheba_message', models.TextField(blank=True, default=None, null=True)),
                ('phone_message', models.TextField(blank=True, default=None, null=True)),
                ('birth_date', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_sheba_valid', models.BooleanField(blank=True, default=False)),
                ('is_phone_valid', models.BooleanField(blank=True, default=False)),
                ('is_valid', models.BooleanField(blank=True, default=False)),
                ('is_new', models.BooleanField(blank=True, default=False)),
                ('is_main', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='config.config')),
                ('survey_fillout', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyfillout')),
                ('visit', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
    ]
