# Generated by Django 4.1.4 on 2024-04-24 09:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_alter_viewmethod_method_loglimiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='limiter',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='limiter',
            name='datetime_last_change',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='roleview',
            name='can_view',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='roleviewmodelfield',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
