# Generated by Django 4.1.4 on 2024-11-03 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0032_authenticationvalidationlog'),
        ('auth_app', '0033_limiter_datetime_created_and_more'),
    ]

    operations = [
    ]
