# Generated by Django 4.1.4 on 2025-02-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_merge_20241103_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='user roles', to='auth_app.role'),
        ),
    ]
