# Generated by Django 4.1.4 on 2025-07-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0035_extendeduser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
