# Generated by Django 4.1.4 on 2025-07-27 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0036_extendeduser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_app_roleassignment', to=settings.AUTH_USER_MODEL),
        ),
    ]
