# Generated by Django 4.1.4 on 2026-10-01 14:01

from django.db import migrations, models
from django.utils import timezone


def invalidate_legacy_codes(apps, schema_editor):
    otp = apps.get_model('auth_app', 'OTP')
    otp.objects.filter(consumed_at__isnull=True).update(
        consumed_at=timezone.now(), otp='', verification_token='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0038_role_asset_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='consumed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(invalidate_legacy_codes, migrations.RunPython.noop),
    ]
