# Generated by Django 4.1.4 on 2023-12-13 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_identifier', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RefTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('indicator', models.IntegerField(blank=True, default=1)),
                ('affects_on', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('has_ref', models.BooleanField(blank=True, default=False)),
                ('needs_special_access', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.TextField(blank=True, editable=False, max_length=42)),
                ('short_address', models.TextField(blank=True, default=None, editable=False, max_length=16, null=True)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('key', models.CharField(max_length=10)),
                ('is_general', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransactionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.currency')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.layer')),
                ('ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.reftransaction')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettransaction')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transactiontype')),
                ('wallet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet')),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettype'),
        ),
    ]
