# Generated by Django 4.1.4 on 2023-12-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransactionType',
            new_name='TransactionLineType',
        ),
    ]
