# Generated by Django 4.1.4 on 2023-12-13 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_transactiontype_transactionlinetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('config', models.TextField()),
                ('min_amount', models.BigIntegerField(blank=True, default=None, null=True)),
                ('max_amount', models.BigIntegerField(blank=True, default=None, null=True)),
                ('users_hint', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='layer',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(help_text='it is key for this table!', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='AllowedTransactionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.layer')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.transactiontype')),
                ('wallet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettype')),
            ],
        ),
    ]
