# Generated by Django 4.1.4 on 2023-12-24 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transactiontype_layer_is_active_layer_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedtransactionrule',
            name='currency',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.currency'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='max_acceptable_rest_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='rest_config',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.transactiontype'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
