# Generated by Django 4.1.4 on 2023-12-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_allowedtransactionrule_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reftransaction',
            name='data',
            field=models.TextField(),
        ),
    ]
