# Generated by Django 4.2.8 on 2023-12-31 16:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_reftransaction_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signature_identifier',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='short_address',
            field=models.TextField(blank=True, default=None, editable=False, max_length=16, null=True, unique=True),
        ),
    ]
