# Generated by Django 4.2.8 on 2023-12-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_account_signature_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='users_hint',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
