# Generated by Django 4.2 on 2024-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_transactiontype_users_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.BigIntegerField()),
            ],
        ),
    ]
