# Generated by Django 4.2 on 2024-02-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_variableconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedtransactionrule',
            name='wallet_type',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallettype'),
        ),
    ]
