# Generated by Django 4.2 on 2024-05-04 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_alter_allowedtransactionrule_wallet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reftransaction',
            name='data',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='wallettype',
            name='key',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
