# Generated by Django 4.2 on 2024-05-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0010_reftransaction_bank_charge_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='datetime_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='datetime_last_change',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
