# Generated by Django 4.2 on 2024-05-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_wallettransaction_datetime_created_and_more'),
    ]

    operations = [
    ]
