# Generated by Django 4.2 on 2024-05-14 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0012_reftransaction_outer_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, default='JV_CREDIT', max_length=18, null=True)),
                ('amount_rials', models.BigIntegerField(default=0)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('datetime_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_last_change', models.DateTimeField(blank=True, default=None, null=True)),
                ('buyer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeForWalletInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('verification_token', models.TextField(blank=True)),
                ('datetime_requested', models.DateTimeField(blank=True, default=None, null=True)),
                ('wallet_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.walletinvoice')),
            ],
        ),
        migrations.AddField(
            model_name='reftransaction',
            name='wallet_invoice',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.walletinvoice'),
        ),
    ]
