# Generated by Django 4.2 on 2024-06-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_walletinvoice_codeforwalletinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletinvoice',
            name='is_closed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='walletinvoice',
            name='payable_amount_rials',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
