# Generated by Django 4.2 on 2024-06-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0014_walletinvoice_is_closed_and_more'),
    ]

    operations = [

    ]
