# Generated by Django 4.2 on 2024-07-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_walletinvoice_store_loyalty_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial')], default='INITIAL', max_length=18),
        ),
    ]
