# Generated by Django 4.2 on 2024-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0016_walletinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial')], default='INITIAL', max_length=18),
        ),
    ]
