# Generated by Django 4.2 on 2024-07-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_walletinvoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='is_reversed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial'), ('REVERSE', 'Reverse')], default='INITIAL', max_length=18),
        ),
    ]
