# Generated by Django 4.2 on 2024-08-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_wallettransaction_is_reversed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial'), ('REVERSE', 'Reverse')], default='INITIAL', max_length=18),
        ),
    ]
