# Generated by Django 4.2 on 2024-10-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0027_alter_walletinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial'), ('REVERSE', 'Reverse')], default='INITIAL', max_length=18),
        ),
    ]
