# Generated by Django 4.2 on 2024-12-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0058_alter_walletinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial'), ('REVERSE', 'Reverse')], default='INITIAL', max_length=18),
        ),
        migrations.AlterField(
            model_name='walletinvoice',
            name='type',
            field=models.CharField(blank=True, choices=[('JV_CREDIT', 'Jv Credit'), ('BLU_CREDIT', 'Blu Credit')], max_length=50, null=True),
        ),
    ]
