# Generated by Django 4.1.4 on 2025-01-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0064_walletinvoice_visit_alter_walletinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'Paid'), ('INITIAL', 'Initial'), ('REVERSE', 'Reverse')], default='INITIAL', max_length=18),
        ),
    ]
