# Generated by Django 4.1.4 on 2025-02-25 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0066_alter_walletinvoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletinvoice',
            name='status',
            field=models.CharField(blank=True, choices=[('PAID', 'PAID'), ('INITIAL', 'INITIAL'), ('REVERSE', 'REVERSE')], default='INITIAL', max_length=18),
        ),
        migrations.AlterField(
            model_name='walletinvoice',
            name='type',
            field=models.CharField(blank=True, choices=[('JV_CREDIT', 'JV_CREDIT'), ('BLU_CREDIT', 'BLU_CREDIT')], max_length=50, null=True),
        ),
    ]
