# Generated by Django 4.1.4 on 2025-03-01 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallet', '0067_alter_walletinvoice_status_alter_walletinvoice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletinvoice',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='walletinvoice',
            name='seller',
        ),
        migrations.AddField(
            model_name='walletinvoice',
            name='client',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walletinvoice',
            name='expert',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_expert', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='walletinvoice',
            name='type',
            field=models.CharField(blank=True, choices=[('CREDIT', 'CREDIT'), ('CASH', 'CASH'), ('POS', 'POS'), ('OTHER', 'OTHER')], max_length=50, null=True),
        ),
    ]
