# Generated by Django 4.1.4 on 2022-12-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0002_otp_datetime_requested_alter_extendeduser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutletCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_en', models.CharField(max_length=50)),
                ('brand_fa', models.CharField(max_length=50)),
                ('product_category', models.CharField(choices=[('WM', 'WM'), ('DW', 'DW'), ('RF', 'RF'), ('VC', 'VC'), ('AC', 'AC'), ('OT', 'OT')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GE', 'General'), ('SH', 'Shelf')], max_length=2)),
                ('text', models.TextField()),
                ('short_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('answer_type', models.CharField(choices=[('YN', 'Yes/No'), ('MC', 'MultiChoices'), ('SC', 'Score'), ('DE', 'Description'), ('NO', 'Number'), ('PR', 'Price')], max_length=2)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('priority', models.IntegerField(blank=True, default=None, null=True)),
                ('outlet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outletcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.TextField(max_length=1000)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('mobile_phone', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('owner_national_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('period', models.IntegerField(blank=True, default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outletcategory')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.city')),
            ],
        ),
    ]
