# Generated by Django 4.1.4 on 2022-12-19 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('field', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.product'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer_type',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_turn', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('checked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checker', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outlet')),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min', models.IntegerField(blank=True, default=1)),
                ('max', models.IntegerField(blank=True, default=20)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
                ('outlet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outletcategory')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.question')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.phototype')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('bool', models.BooleanField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('price', models.BigIntegerField(blank=True, default=None, null=True)),
                ('multichoice', models.ManyToManyField(blank=True, related_name='Answers', to='visit.answerchoice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.question')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answer_choices',
            field=models.ManyToManyField(related_name='Valid_Answers', to='visit.answerchoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_type',
            field=models.ManyToManyField(to='visit.answertype'),
        ),
    ]
