# Generated by Django 4.1.4 on 2022-12-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0002_answerchoice_answertype_product_model_product_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='visit_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='is_mandatory',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
