# Generated by Django 4.1.4 on 2022-12-21 10:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0003_outlet_visit_count_question_is_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phototype',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.question'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='checked_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker', to=settings.AUTH_USER_MODEL),
        ),
    ]
