# Generated by Django 4.1.4 on 2022-12-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_alter_phototype_question_alter_visit_checked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcategory',
            name='icon',
            field=models.URLField(default=None, null=True),
        ),
    ]
