# Generated by Django 4.1.4 on 2022-12-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_outletcategory_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='code',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='pakshoma_code',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
