# Generated by Django 4.1.4 on 2022-12-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_outlet_code_outlet_pakshoma_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('GE', 'General'), ('SH', 'Shelf'), ('SA', 'SA')], max_length=2),
        ),
    ]
