# Generated by Django 4.1.4 on 2022-12-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0008_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototype',
            name='verbose_name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
