# Generated by Django 4.1.4 on 2022-12-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0009_phototype_verbose_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Census',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porslineid', models.CharField(default=None, max_length=20, null=True)),
                ('province', models.CharField(default=None, max_length=60, null=True)),
                ('city', models.CharField(default=None, max_length=60, null=True)),
                ('storefront_photo', models.TextField(default=None, null=True)),
                ('store_situation', models.TextField(default=None, null=True)),
                ('store_name', models.CharField(default=None, max_length=120, null=True)),
                ('store_owner', models.CharField(default=None, max_length=40, null=True)),
                ('store_address', models.TextField(default=None, null=True)),
                ('postalcode', models.CharField(default=None, max_length=10, null=True)),
                ('phone', models.CharField(default=None, max_length=20, null=True)),
                ('mobile', models.CharField(default=None, max_length=20, null=True)),
                ('banknum', models.CharField(default=None, max_length=50, null=True)),
                ('boardlable', models.CharField(default=None, max_length=120, null=True)),
                ('meter', models.IntegerField(default=None, null=True)),
                ('isavailable', models.BooleanField(default=None, null=True)),
                ('hamakri', models.BooleanField(default=None, null=True)),
                ('visitcard_photo', models.TextField(default=None, null=True)),
                ('vitrin_photo', models.TextField(default=None, null=True)),
                ('gift_photo', models.TextField(default=None, null=True)),
                ('pop_photo', models.TextField(default=None, null=True)),
                ('selfie_photo', models.TextField(default=None, null=True)),
                ('promoter_code', models.CharField(default=None, max_length=50, null=True)),
                ('location', models.CharField(default=None, max_length=60, null=True)),
                ('start_date', models.CharField(default=None, max_length=30, null=True)),
                ('finish_date', models.CharField(default=None, max_length=30, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together={('outlet', 'visit_turn', 'is_deleted')},
        ),
    ]
