# Generated by Django 4.1.4 on 2022-12-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0010_census_alter_visit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='mobile_phone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
