# Generated by Django 4.1.4 on 2022-12-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0011_alter_outlet_mobile_phone_alter_outlet_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
