# Generated by Django 4.1.4 on 2022-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0012_photo_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='is_visiting',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
