# Generated by Django 4.1.4 on 2022-12-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0013_outlet_is_visiting'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='visit',
            name='rejection_reason',
            field=models.TextField(default=None, null=True),
        ),
    ]
