# Generated by Django 4.1.4 on 2022-12-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0014_alter_visit_unique_together_visit_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='census',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
