# Generated by Django 4.1.4 on 2022-12-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0015_census_latitude_census_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True),
        ),
        migrations.AlterField(
            model_name='census',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True),
        ),
    ]
