# Generated by Django 4.1.4 on 2022-12-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0016_alter_census_latitude_alter_census_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='rejection_reason',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
