# Generated by Django 4.1.4 on 2023-01-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0017_alter_visit_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
