# Generated by Django 4.1.4 on 2023-01-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0018_question_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='census',
            name='photo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
