# Generated by Django 4.1.4 on 2023-01-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0019_census_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='start_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
