# Generated by Django 4.1.4 on 2023-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0020_visit_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='mobile',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='census',
            name='phone',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
