# Generated by Django 4.1.4 on 2023-01-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0021_alter_census_mobile_alter_census_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldsTranstaltion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
