# Generated by Django 4.1.4 on 2023-01-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0022_fieldstranstaltion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldstranstaltion',
            name='value',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
