# Generated by Django 4.1.4 on 2023-01-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0023_alter_fieldstranstaltion_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='customer_category',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
