# Generated by Django 4.1.4 on 2023-01-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0024_question_customer_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='census',
            name='boardlable',
            field=models.CharField(default=None, max_length=150, null=True),
        ),
    ]
