# Generated by Django 4.1.4 on 2023-01-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0025_alter_census_boardlable'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='owner_name',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
    ]
