# Generated by Django 4.1.4 on 2023-01-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0026_outlet_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='phototype',
            name='report_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.reportcategory'),
        ),
        migrations.AddField(
            model_name='question',
            name='report_category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.reportcategory'),
        ),
    ]
