# Generated by Django 4.1.4 on 2023-01-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0027_reportcategory_phototype_report_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototype',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
