# Generated by Django 4.1.4 on 2023-01-23 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0028_phototype_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='outlet_category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.outletcategory'),
        ),
    ]
