# Generated by Django 4.1.4 on 2023-01-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0029_reportcategory_outlet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('GE', 'General'), ('SH', 'Shelf'), ('SA', 'Sale'), ('V', 'V')], max_length=2),
        ),
    ]
