# Generated by Django 4.1.4 on 2023-01-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0030_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototype',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
