# Generated by Django 4.1.4 on 2023-02-05 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0031_phototype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.CharField(default='', max_length=40)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('outlet_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outletcategory')),
                ('report_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.reportcategory')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.questiontype'),
        ),
    ]
