# Generated by Django 4.1.4 on 2023-02-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0032_questiontype_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('GE', 'General'), ('SH', 'Shelf'), ('SA', 'Sale'), ('V', 'V'), ('FA', 'FA')], max_length=2),
        ),
    ]
