# Generated by Django 4.1.4 on 2023-03-01 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0033_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='comment_publisher',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_comment',
            field=models.TextField(default=None, null=True),
        ),
    ]
