# Generated by Django 4.1.4 on 2023-04-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0035_alter_visit_comment_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='bool_is_correct',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bool_expected_value',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='FoulAlarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('answers', models.ManyToManyField(to='visit.answer')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outlet')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.question')),
            ],
        ),
    ]
