# Generated by Django 4.1.4 on 2023-04-05 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0036_answer_bool_is_correct_question_bool_expected_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='bool_is_correct',
            new_name='bool_is_expected',
        ),
    ]
