# Generated by Django 4.1.4 on 2023-04-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0037_rename_bool_is_correct_answer_bool_is_expected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='bool_expected_value',
            new_name='bool_unexpected_value',
        ),
    ]
