# Generated by Django 4.1.4 on 2023-04-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0038_rename_bool_expected_value_question_bool_unexpected_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='has_bool_expected_value',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
