# Generated by Django 4.1.4 on 2023-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0039_question_has_bool_expected_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertype',
            name='priority',
            field=models.BigIntegerField(default=1),
        ),
    ]
