# Generated by Django 4.1.4 on 2023-04-20 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_role_roleassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0040_answertype_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=35, null=True)),
                ('subject', models.CharField(blank=True, default=None, max_length=60, null=True)),
                ('status', models.CharField(choices=[('W', 'Waiting'), ('A', 'Answered'), ('C', 'Closed')], default='W', max_length=1)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.outlet')),
                ('role_assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.role')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, default=None, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TicketMessageParent', to='visit.ticketmessage')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='TicketMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('ticket_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.ticketmessage')),
            ],
        ),
    ]
