# Generated by Django 4.1.4 on 2023-04-20 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_role_roleassignment'),
        ('visit', '0041_ticket_ticketmessage_ticketmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmessage',
            name='created_by_role_assignment',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.roleassignment'),
        ),
    ]
