# Generated by Django 4.1.4 on 2023-04-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0042_ticketmessage_created_by_role_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='outlet',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.outlet'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='visit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
    ]
