# Generated by Django 4.1.4 on 2023-04-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0044_alter_ticket_creator_alter_ticket_outlet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(blank=True, choices=[('W', 'Waiting'), ('A', 'Answered'), ('C', 'Closed')], default='W', max_length=1),
        ),
    ]
