# Generated by Django 4.1.4 on 2023-04-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_role_roleassignment'),
        ('visit', '0045_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_by_role_assignment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.roleassignment'),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TicketMessageParent', to='visit.ticketmessage'),
        ),
    ]
