# Generated by Django 4.1.4 on 2023-04-26 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0046_alter_ticketmessage_created_by_role_assignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmessage',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
