# Generated by Django 4.1.4 on 2023-05-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0047_alter_ticketmessage_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('icon', models.TextField(blank=True, default=None, null=True)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('questions', models.ManyToManyField(to='visit.question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='datetime_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='datetime_last_change',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
        migrations.CreateModel(
            name='SurveyFillOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.survey')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='survey_fill_out',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.surveyfillout'),
        ),
    ]
