# Generated by Django 4.1.4 on 2023-05-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0048_survey_answer_datetime_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyfillout',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='survey_fill_out',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyFillOut',
        ),
    ]
