# Generated by Django 4.1.4 on 2023-05-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0049_remove_surveyfillout_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
