# Generated by Django 4.1.4 on 2023-05-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_project_supervisor_adminmenu_roleassignment_project_and_more'),
        ('visit', '0050_answer_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlet',
            old_name='pakshoma_code',
            new_name='customer_code',
        ),
        migrations.AddField(
            model_name='outletcategory',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='phototype',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
    ]
