# Generated by Django 4.1.4 on 2023-05-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0051_rename_pakshoma_code_outlet_customer_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dropdown',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dropdown', to='visit.answerchoice'),
        ),
        migrations.AddField(
            model_name='answer',
            name='radio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio', to='visit.answerchoice'),
        ),
    ]
