# Generated by Django 4.1.4 on 2023-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0052_answer_dropdown_answer_radio'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='dropdown_choices',
            field=models.ManyToManyField(related_name='dropdown_choices', to='visit.answerchoice'),
        ),
        migrations.AddField(
            model_name='question',
            name='radio_choices',
            field=models.ManyToManyField(related_name='radio_choices', to='visit.answerchoice'),
        ),
    ]
