# Generated by Django 4.1.4 on 2023-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0053_question_dropdown_choices_question_radio_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
