# Generated by Django 4.1.4 on 2023-06-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0054_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototype',
            name='is_supervision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='is_supervision',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='due_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='has_due_date',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
