# Generated by Django 4.1.4 on 2023-06-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_surveyfillout_visit'),
        ('auth_app', '0012_uploadedfile_name_uploadedfile_type'),
        ('visit', '0055_phototype_is_supervision_questiontype_is_supervision_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phototype',
            old_name='is_supervision',
            new_name='is_for_supervision',
        ),
        migrations.RenameField(
            model_name='questiontype',
            old_name='is_supervision',
            new_name='is_for_supervision',
        ),
        migrations.AddField(
            model_name='visit',
            name='supervision_status',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='0', max_length=1),
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('has_supervision', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('project', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
                ('surveys', models.ManyToManyField(to='survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visittype'),
        ),
    ]
