# Generated by Django 4.1.4 on 2023-06-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0057_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='code',
            field=models.CharField(blank=True, default='1', max_length=20, null=True),
        ),
    ]
