# Generated by Django 4.1.4 on 2023-07-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0058_alter_outlet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='outletcategory',
            name='verbose_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
