# Generated by Django 4.1.4 on 2023-07-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0059_outletcategory_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='answer',
            field=models.CharField(max_length=100),
        ),
    ]
