# Generated by Django 4.1.4 on 2023-07-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0060_alter_answerchoice_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcategory',
            name='is_for_supervision',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
