# Generated by Django 4.1.4 on 2023-07-29 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0061_reportcategory_is_for_supervision'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoreInfoKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default=None, max_length=255, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.moreinfokey')),
            ],
        ),
        migrations.AddField(
            model_name='outlet',
            name='more_info',
            field=models.ManyToManyField(to='visit.moreinfo'),
        ),
    ]
