# Generated by Django 4.1.4 on 2023-08-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0062_moreinfokey_moreinfo_outlet_more_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='decision_rank',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_for_decision',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
