# Generated by Django 4.1.4 on 2023-09-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0063_question_decision_rank_question_is_for_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='customer_code',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
