# Generated by Django 4.1.4 on 2023-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0064_alter_outlet_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='recognition_status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
