# Generated by Django 4.1.4 on 2023-10-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0065_photo_recognition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='phototype',
            name='visit_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visittype'),
        ),
        migrations.AddField(
            model_name='questiontype',
            name='visit_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visittype'),
        ),
        migrations.AddField(
            model_name='reportcategory',
            name='visit_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visittype'),
        ),
    ]
