# Generated by Django 4.1.4 on 2024-01-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0067_photo_supervision_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='is_last_day',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
