# Generated by Django 4.1.4 on 2024-01-20 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0023_region_district'),
        ('visit', '0068_visit_is_last_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='district',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.district'),
        ),
        migrations.AddField(
            model_name='outlet',
            name='region',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.region'),
        ),
    ]
