# Generated by Django 4.1.4 on 2024-02-22 12:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0069_outlet_district_outlet_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visit_turn',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='VisitRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10000), django.core.validators.MinValueValidator(0)])),
                ('datetime_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_last_change', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('photo_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.phototype')),
                ('question_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.questiontype')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
            options={
                'unique_together': {('created_by', 'visit', 'question_type', 'photo_type')},
            },
        ),
    ]
