# Generated by Django 4.1.4 on 2024-06-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_addin_delete_authenticationvalidationlog'),
        ('visit', '0072_answer_latitude_answer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittype',
            name='add_ins',
            field=models.ManyToManyField(to='config.addin'),
        ),
    ]
