# Generated by Django 4.1.4 on 2025-01-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_merge_20241103_1156'),
        ('survey', '0026_remove_outerentryconfig_outlet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0074_photo_is_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Apartment', 'Apartment'), ('Complex', 'Complex')], default='Complex', max_length=10)),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('is_visiting', models.BooleanField(blank=True, default=False)),
                ('code', models.CharField(max_length=25)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.city')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_building', to='visit.building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.building')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingElevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.building')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('avatar_photo', models.TextField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(choices=[('Customer', 'Customer'), ('Business', 'Business')], default='Customer', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('capacity', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('number_of_floors', models.IntegerField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ProductElevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.elevator')),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('model_number', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('type', models.CharField(blank=True, default=None, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='outletcategory',
            name='project',
        ),
        migrations.RemoveField(
            model_name='foulalarm',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='foulalarm',
            name='datetime_created',
        ),
        migrations.RemoveField(
            model_name='foulalarm',
            name='datetime_last_change',
        ),
        migrations.RemoveField(
            model_name='foulalarm',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='foulalarm',
            name='question',
        ),
        migrations.RemoveField(
            model_name='phototype',
            name='outlet_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_en',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_fa',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='project',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='question',
            name='outlet_category',
        ),
        migrations.RemoveField(
            model_name='questiontype',
            name='outlet_category',
        ),
        migrations.RemoveField(
            model_name='reportcategory',
            name='outlet_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='outlet',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='outlet',
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_question', to='visit.question'),
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='datetime_last_change',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_used',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.DeleteModel(
            name='Outlet',
        ),
        migrations.DeleteModel(
            name='OutletCategory',
        ),
        migrations.AddField(
            model_name='productelevator',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.product'),
        ),
        migrations.AddField(
            model_name='client',
            name='visit_types',
            field=models.ManyToManyField(to='visit.visit'),
        ),
        migrations.AddField(
            model_name='buildingelevator',
            name='elevator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.elevator'),
        ),
        migrations.AddField(
            model_name='buildingclient',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.client'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='building',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.building'),
        ),
        migrations.AddField(
            model_name='visit',
            name='building',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.building'),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.productmodel'),
        ),
    ]
