# Generated by Django 4.1.4 on 2025-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0076_visit_expert_alter_visit_promoter'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerchoice',
            name='score',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='prevented_by_score',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
