# Generated by Django 4.1.4 on 2025-03-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0077_answerchoice_score_visit_prevented_by_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='visittype',
            name='default_wage',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
