# Generated by Django 4.1.4 on 2025-03-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0078_visittype_default_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='total_wage',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
