# Generated by Django 4.1.4 on 2025-03-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0079_visit_total_wage'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='elevator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visit_elevator', to='visit.elevator'),
        ),
    ]
