# Generated by Django 4.1.4 on 2025-05-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0080_visit_elevator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='elevator',
        ),
        migrations.AddField(
            model_name='visit',
            name='elevator',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='visit_elevator', to='visit.elevator'),
        ),
    ]
