# Generated by Django 4.1.4 on 2025-06-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0081_remove_visit_elevator_visit_elevator'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='cabin_capacity_kg',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='control_panel_brand',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='control_panel_image',
            field=models.TextField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='control_panel_serial',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='control_panel_type',
            field=models.CharField(blank=True, choices=[('MR', 'MR'), ('MRL', 'MRL')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='control_system_type',
            field=models.CharField(blank=True, choices=[('OPEN_LOOP', 'OPEN_LOOP'), ('CLOSED_LOOP', 'CLOSED_LOOP')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door1_type',
            field=models.CharField(blank=True, choices=[('SWING', 'SWING'), ('SEMI_AUTO', 'SEMI_AUTO'), ('AUTO', 'AUTO')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door1_voltage',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door2_type',
            field=models.CharField(blank=True, choices=[('SWING', 'SWING'), ('SEMI_AUTO', 'SEMI_AUTO'), ('AUTO', 'AUTO')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door2_voltage',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door3_type',
            field=models.CharField(blank=True, choices=[('SWING', 'SWING'), ('SEMI_AUTO', 'SEMI_AUTO'), ('AUTO', 'AUTO')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door3_voltage',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door_brand',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='door_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_speed_mps',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='elevator_type',
            field=models.CharField(blank=True, choices=[('TRACTION', 'TRACTION'), ('HYDRAULIC', 'HYDRAULIC')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='emergency_system_type',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('UPS', 'UPS'), ('HDRU', 'HDRU')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='firefighter_mode',
            field=models.CharField(blank=True, choices=[('INACTIVE', 'INACTIVE'), ('MODE1', 'MODE1'), ('MODE2', 'MODE2')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='input_voltage',
            field=models.CharField(blank=True, choices=[('SINGLE_PHASE', 'SINGLE_PHASE'), ('THREE_PHASE', 'THREE_PHASE'), ('OTHER', 'OTHER')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='inverter_power',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='inverter_type',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='landing_call_comm_type',
            field=models.CharField(blank=True, choices=[('SERIAL', 'SERIAL'), ('PARALLEL', 'PARALLEL')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='motor_brand',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='motor_encoder_type',
            field=models.CharField(blank=True, choices=[('1024_24V', '1024_24V'), ('1024_5V', '1024_5V'), ('ERN_1387', 'ERN_1387'), ('ERN_1313', 'ERN_1313'), ('ERN_413', 'ERN_413'), ('OTHER', 'OTHER')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='motor_nameplate_image',
            field=models.TextField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='motor_power_kw',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='motor_type',
            field=models.CharField(blank=True, choices=[('GEARED', 'GEARED'), ('GEARLESS', 'GEARLESS')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='operation_type',
            field=models.CharField(blank=True, choices=[('SIMPLEX', 'SIMPLEX'), ('DUPLEX', 'DUPLEX'), ('GROUP', 'GROUP')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='standard_type',
            field=models.CharField(blank=True, choices=[('EN81', 'EN81'), ('EN81-20', 'EN81-20')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='stops_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('RESIDENTIAL', 'RESIDENTIAL'), ('OFFICE', 'OFFICE'), ('COMMERCIAL', 'COMMERCIAL'), ('INDUSTRIAL', 'INDUSTRIAL')], default=None, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='weight_sensor',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('EXISTS', 'EXISTS')], default=None, max_length=25, null=True),
        ),
    ]
