# Generated by Django 4.1.4 on 2025-07-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0083_alter_visit_status_alter_visit_supervision_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
