# Generated by Django 4.1.4 on 2025-08-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0085_alter_visit_status_alter_visit_supervision_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(default='')),
                ('score_begin', models.IntegerField()),
                ('score_end', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.visit')),
            ],
        ),
    ]
