# Generated by Django 4.1.4 on 2026-10-01 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0037_alter_roleassignment_user'),
        ('visit', '0086_visitrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('verbose_name', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=25)),
                ('customer_code', models.CharField(blank=True, default='', max_length=25)),
                ('phone', models.CharField(blank=True, default='', max_length=16)),
                ('mobile_phone', models.CharField(blank=True, default='', max_length=16)),
                ('owner_name', models.CharField(blank=True, default='', max_length=255)),
                ('owner_national_code', models.CharField(blank=True, default='', max_length=10)),
                ('address', models.TextField(blank=True, default='')),
                ('postal_code', models.CharField(blank=True, default='', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('period', models.PositiveIntegerField(default=1)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visiting', models.BooleanField(default=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visit.storecategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_app.city')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='store',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='store_project_code_unique'),
        ),
    ]
