# Generated by Django 4.1.4 on 2026-10-01 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_app', '0038_role_asset_scope'),
        ('visit', '0088_asset_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_key', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.project')),
                ('visits', models.ManyToManyField(related_name='service_submissions', to='visit.visit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='servicerequestsubmission',
            constraint=models.UniqueConstraint(fields=('project', 'creator', 'request_key'), name='service_request_user_key_unique'),
        ),
    ]
