# Generated by Django 4.1.4 on 2026-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0089_service_request_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingclient',
            name='end_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='buildingclient',
            name='start_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
