# Generated by Django 4.1.4 on 2026-10-01 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0090_buildingclient_end_at_buildingclient_start_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingclient',
            name='end_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='buildingclient',
            name='ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managements_ended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='buildingclient',
            name='start_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='buildingclient',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managements_started', to=settings.AUTH_USER_MODEL),
        ),
    ]
