# Generated by Django 4.1.4 on 2026-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0092_client_visit_type_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='elevator',
            field=models.ManyToManyField(blank=True, related_name='visit_elevator', to='visit.elevator'),
        ),
    ]
