# Generated by Django 4.1.4 on 2026-10-01 15:13

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
import django.db.models.deletion


def require_unique_active_products(apps, schema_editor):
    links = apps.get_model('visit', 'ProductElevator')
    duplicate_count = (links.objects.using(schema_editor.connection.alias)
                       .filter(is_active=True).values('product_id')
                       .annotate(link_count=Count('pk')).filter(link_count__gt=1).count())
    if duplicate_count:
        raise RuntimeError(
            f'{duplicate_count} products have multiple active installations; '
            'reconcile these links before applying the uniqueness constraint.'
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0093_alter_visit_elevator'),
    ]

    operations = [
        migrations.AddField(
            model_name='productelevator',
            name='installed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productelevator',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productelevator',
            name='removal_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='productelevator',
            name='removed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productelevator',
            name='removed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_removals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(require_unique_active_products, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='productelevator',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('product',), name='visit_one_active_installation_per_product'),
        ),
    ]
