# Generated by Django 4.1.4 on 2026-10-01 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0095_warranty_repair_cases'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitReportSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('checksum', models.CharField(max_length=64)),
                ('source', models.CharField(default='completion', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_snapshots', to='visit.visit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='visitreportsnapshot',
            constraint=models.UniqueConstraint(fields=('visit', 'version'), name='visit_report_snapshot_version_unique'),
        ),
    ]
