# Generated by Django 4.1.4 on 2026-10-01 17:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0096_visitreportsnapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVisitFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('note', models.CharField(blank=True, default='', max_length=1000)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_feedback', to='visit.visit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='clientvisitfeedback',
            constraint=models.UniqueConstraint(fields=('visit', 'user'), name='client_visit_feedback_user_unique'),
        ),
    ]
