# Generated by Django 4.1.4 on 2026-10-02 16:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0043_admin_dashboard_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0097_clientvisitfeedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('target', models.CharField(choices=[('client', 'مشتری'), ('building', 'ساختمان'), ('elevator', 'آسانسور')], max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('default_value', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority_factors', to='auth_app.project')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='building',
            name='priority_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='priority_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='elevator',
            name='priority_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='PriorityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('value', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='visit.priorityfactor')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PriorityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_assignments', to='visit.building')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_assignments', to='visit.client')),
                ('elevator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='priority_assignments', to='visit.elevator')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visit.priorityfactor')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='visit.priorityoption')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='priorityassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('building__isnull', True), ('client__isnull', False), ('elevator__isnull', True)), models.Q(('building__isnull', False), ('client__isnull', True), ('elevator__isnull', True)), models.Q(('building__isnull', True), ('client__isnull', True), ('elevator__isnull', False)), _connector='OR'), name='priority_assignment_one_target'),
        ),
        migrations.AddConstraint(
            model_name='priorityassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('factor', 'client'), name='priority_unique_client_factor'),
        ),
        migrations.AddConstraint(
            model_name='priorityassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('building__isnull', False)), fields=('factor', 'building'), name='priority_unique_building_factor'),
        ),
        migrations.AddConstraint(
            model_name='priorityassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('elevator__isnull', False)), fields=('factor', 'elevator'), name='priority_unique_elevator_factor'),
        ),
    ]
