# Generated by Django 4.1.4 on 2026-10-02 16:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0044_priority_grants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0098_priority_scoring'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='completion_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='visit',
            name='completion_code_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='completion_code_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visittype',
            name='requires_client_code',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='VisitAssignmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accepted', 'پذیرش'), ('declined', 'بازگرداندن')], max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visit_assignment_events', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_events', to='visit.visit')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(730)])),
                ('lead_days', models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MaxValueValidator(60)])),
                ('next_due', models.DateField()),
                ('note', models.CharField(blank=True, default='', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='visit.elevator')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_plans', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_plans', to='auth_app.project')),
                ('visit_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='visit.visittype')),
            ],
            options={
                'ordering': ('next_due', 'id'),
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='maintenance_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='visit.maintenanceplan'),
        ),
    ]
