# Generated by Django 4.2 on 2024-05-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('msg_pattern', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
