# Generated by Django 4.2 on 2024-06-18 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(max_length=255, null=True)),
                ('response_code', models.PositiveSmallIntegerField()),
                ('remote_address', models.CharField(max_length=20, null=True)),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('exec_time', models.IntegerField(null=True)),
                ('datetime_created', models.DateTimeField(blank=True, null=True)),
                ('datetime_response_received', models.DateTimeField(blank=True, null=True)),
                ('referer', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
