# Generated by Django 4.2 on 2024-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_requestlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestlog',
            name='user',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='user_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
