# Generated by Django 4.2 on 2024-08-19 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_alter_conversation_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='date_created',
            new_name='datetime_created',
        ),
    ]
