# Generated by Django 4.2 on 2024-11-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_rename_date_created_conversationmessage_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='sent_data',
            field=models.CharField(max_length=2056, null=True),
        ),
    ]
