# Generated by Django 4.1.4 on 2025-01-06 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0074_photo_is_favourite'),
        ('utils', '0009_requestlog_sent_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
    ]
