# Generated by Django 4.1.4 on 2025-01-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0034_merge_20241103_1156'),
        ('utils', '0010_conversation_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='assigned_person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.roleassignment'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='assigned_role',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.role'),
        ),
    ]
