# Generated by Django 4.1.4 on 2025-01-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0011_conversation_assigned_person_and_more'),
        ('visit', '0075_building_buildingclient_buildingelevator_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='elevator',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.elevator'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.IntegerField(choices=[(1, 'Initial'), (2, 'In Progress'), (3, 'Closed')], default=1),
        ),
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Expert_Client'), (2, 'Admin_Client'), (3, 'Expert_Admin')], default=None, null=True),
        ),
    ]
