# Generated by Django 5.2 on 2025-05-05 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('name_fa', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('abbreviation', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('logo', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.TextField(blank=True, default=None, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('is_active', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('datetime_requested', models.DateTimeField(blank=True)),
                ('verification_token', models.TextField(blank=True)),
                ('wrong_answers_count', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_url', models.CharField(max_length=255, null=True)),
                ('method', models.CharField(max_length=255, null=True)),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('response_code', models.PositiveSmallIntegerField()),
                ('remote_address', models.CharField(max_length=20, null=True)),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('exec_time', models.IntegerField(null=True)),
                ('datetime_created', models.DateTimeField(blank=True, null=True)),
                ('datetime_response_received', models.DateTimeField(blank=True, null=True)),
                ('referer', models.CharField(max_length=255, null=True)),
                ('sent_data', models.CharField(max_length=2056, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(blank=True, verbose_name='datetime created')),
                ('datetime_last_change', models.DateTimeField(blank=True, verbose_name='datetime last change')),
                ('role_title', models.CharField(max_length=90, unique=True, verbose_name='role title')),
                ('description', models.TextField(verbose_name='role description')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('category', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('initial', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('is_active', models.BooleanField(blank=True, default=False)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.province')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('last_name', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('national_code', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('job', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('sheba', models.CharField(blank=True, default=None, max_length=26, null=True)),
                ('landline_phone', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('gender', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roles', models.ManyToManyField(blank=True, help_text='user roles', to='main.role')),
                ('hair_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hair_type', to='main.specificationtype')),
                ('job_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_type', to='main.specificationtype')),
                ('skin_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skin_type', to='main.specificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, default=None, null=True)),
                ('postal_code', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_last_change', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.city')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_type', to='main.specificationtype')),
            ],
        ),
        migrations.CreateModel(
            name='ViewMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=255, verbose_name='view name')),
                ('method', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('is_public', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'unique_together': {('view_name', 'method')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='allowed_view_methods',
            field=models.ManyToManyField(blank=True, help_text='any user with this role has permission to', to='main.viewmethod'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['province'], name='main_city_provinc_9d210f_idx'),
        ),
    ]
