# Generated by Django 4.1.4 on 2023-05-03 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visit', '0049_remove_surveyfillout_survey_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('verbose_name', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('icon', models.TextField(blank=True, default=None, null=True)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyReportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.CharField(default='', max_length=40)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('survey_report_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyreportcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('short_text', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('has_bool_expected_value', models.BooleanField(blank=True, default=False)),
                ('bool_unexpected_value', models.BooleanField(blank=True, default=None, null=True)),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('priority', models.IntegerField(blank=True, default=None, null=True)),
                ('customer_category', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('answer_choices', models.ManyToManyField(related_name='Survey_Valid_Answers', to='visit.answerchoice')),
                ('answer_type', models.ManyToManyField(to='visit.answertype')),
                ('survey_question_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestiontype')),
                ('survey_report_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyreportcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('verbose_name', models.CharField(default='', max_length=40)),
                ('min', models.IntegerField(blank=True, default=1)),
                ('max', models.IntegerField(blank=True, default=20)),
                ('is_mandatory', models.BooleanField(blank=True, default=False)),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('survey_question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
                ('survey_report_category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyreportcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default=None, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('survey_photo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyphototype')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyFillOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('is_closed', models.BooleanField(blank=True, default=False)),
                ('datetime_created', models.DateTimeField(blank=True)),
                ('datetime_last_change', models.DateTimeField(blank=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, default=None, null=True)),
                ('number', models.IntegerField(blank=True, default=None, null=True)),
                ('bool', models.BooleanField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('price', models.BigIntegerField(blank=True, default=None, null=True)),
                ('bool_is_expected', models.BooleanField(blank=True, default=None, null=True)),
                ('datetime_created', models.DateTimeField(blank=True, default=None, null=True)),
                ('datetime_last_change', models.DateTimeField(blank=True, default=None, null=True)),
                ('multichoice', models.ManyToManyField(blank=True, related_name='SurveyAnswers', to='visit.answerchoice')),
                ('survey_fill_out', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyfillout')),
                ('survey_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestion')),
            ],
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_questions',
            field=models.ManyToManyField(to='survey.surveyquestion'),
        ),
    ]
