# Generated by Django 4.1.4 on 2023-05-03 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_validation'),
        ('survey', '0002_surveyanswer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='survey_questions',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='validation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.validation'),
        ),
    ]
