# Generated by Django 4.1.4 on 2023-05-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_rename_validation_fieldvalidation'),
        ('survey', '0003_remove_survey_survey_questions_surveyquestion_survey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfillout',
            name='city',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.city'),
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='phone_number',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='phone_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='province',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.province'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='has_phone_verification',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.CreateModel(
            name='FillOutPhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16)),
                ('code', models.CharField(blank=True, max_length=5)),
                ('verification_token', models.TextField(blank=True)),
                ('datetime_requested', models.DateTimeField(blank=True, default=None, null=True)),
                ('survey_fill_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.surveyfillout')),
            ],
        ),
    ]
