# Generated by Django 4.1.4 on 2023-05-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_surveyfillout_city_surveyfillout_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyphoto',
            name='survey_fill_out',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyfillout'),
        ),
    ]
