# Generated by Django 4.1.4 on 2023-05-10 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_surveyphoto_survey_fill_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='has_phone_verification',
        ),
        migrations.AddField(
            model_name='survey',
            name='has_phone_verification',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
