# Generated by Django 4.1.4 on 2023-05-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_project_supervisor_adminmenu_roleassignment_project_and_more'),
        ('survey', '0006_remove_surveyquestion_has_phone_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='project',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.project'),
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Initial'), ('1', 'Completed'), ('2', 'Confirmed')], default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='surveyphoto',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
