# Generated by Django 4.1.4 on 2023-05-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_survey_project_surveyfillout_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyphototype',
            name='survey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
