# Generated by Django 4.1.4 on 2023-05-30 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0053_question_dropdown_choices_question_radio_choices'),
        ('survey', '0008_surveyphototype_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='dropdown',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_dropdown', to='visit.answerchoice'),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='radio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survey_radio', to='visit.answerchoice'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='dropdown_choices',
            field=models.ManyToManyField(related_name='survey_dropdown_choices', to='visit.answerchoice'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='radio_choices',
            field=models.ManyToManyField(related_name='survey_radio_choices', to='visit.answerchoice'),
        ),
    ]
