# Generated by Django 4.1.4 on 2023-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_surveyanswer_dropdown_surveyanswer_radio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
