# Generated by Django 4.1.4 on 2023-06-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_surveyquestion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='has_phone_verification',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
