# Generated by Django 4.1.4 on 2023-06-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_alter_survey_has_phone_verification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyfillout',
            unique_together={('survey', 'phone_number')},
        ),
    ]
