# Generated by Django 4.1.4 on 2023-06-08 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_alter_surveyfillout_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='surveyfillout',
            unique_together={('survey', 'phone_number', 'is_deleted')},
        ),
    ]
