# Generated by Django 4.1.4 on 2023-06-19 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0055_phototype_is_supervision_questiontype_is_supervision_and_more'),
        ('survey', '0013_alter_surveyfillout_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfillout',
            name='visit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.visit'),
        ),
    ]
