# Generated by Django 4.1.4 on 2023-07-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_surveyfillout_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='sms_text',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
