# Generated by Django 4.1.4 on 2023-09-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0016_surveyquestion_decision_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyphoto',
            name='recognition_status',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
