# Generated by Django 4.1.4 on 2024-01-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0017_surveyphoto_recognition_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyphoto',
            name='supervision_confirm',
            field=models.CharField(blank=True, choices=[('NOT_CHECKED', 'NOT_CHECKED'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='NOT_CHECKED', max_length=12),
        ),
        migrations.AddField(
            model_name='surveyphoto',
            name='supervision_location_confirm',
            field=models.CharField(blank=True, choices=[('NOT_CHECKED', 'NOT_CHECKED'), ('CONFIRMED', 'CONFIRMED'), ('REJECTED', 'REJECTED')], default='NOT_CHECKED', max_length=12),
        ),
    ]
