# Generated by Django 4.1.4 on 2024-01-30 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0069_outlet_district_outlet_region'),
        ('survey', '0018_surveyphoto_supervision_confirm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyfillout',
            name='outlet',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.outlet'),
        ),
    ]
