# Generated by Django 4.1.4 on 2024-02-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0024_alter_supervisor_unique_together_supervisorchangelog'),
        ('visit', '0069_outlet_district_outlet_region'),
        ('survey', '0019_surveyfillout_outlet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyfillout',
            name='outlet',
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='outer_entry_int_user_id',
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='OuterEntryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, default=None, null=True)),
                ('qr_icon', models.TextField(blank=True, default=None, null=True)),
                ('image', models.TextField(blank=True, default=None, null=True)),
                ('logo', models.TextField(blank=True, default=None, null=True)),
                ('outlet', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.outlet')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
            ],
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='outer_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.outerentryconfig'),
        ),
    ]
