# Generated by Django 4.1.4 on 2024-02-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0020_remove_surveyfillout_outlet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outerentryconfig',
            name='survey',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='surveyfillout',
            name='device_id',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
