# Generated by Django 4.1.4 on 2024-06-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0022_surveyphoto_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True),
        ),
    ]
