# Generated by Django 4.1.4 on 2024-06-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_addin_delete_authenticationvalidationlog'),
        ('survey', '0023_surveyanswer_latitude_surveyanswer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='add_ins',
            field=models.ManyToManyField(to='config.addin'),
        ),
    ]
