# Generated by Django 4.1.4 on 2024-06-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0024_survey_add_ins'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyphoto',
            name='is_favourite',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
