# Generated by Django 4.1.4 on 2025-01-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0025_surveyphoto_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outerentryconfig',
            name='outlet',
        ),
    ]
