# Generated by Django 4.1.4 on 2025-01-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0026_remove_outerentryconfig_outlet'),
        ('visit', '0075_building_buildingclient_buildingelevator_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outerentryconfig',
            name='building',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.building'),
        ),
    ]
