# Generated by Django 4.1.4 on 2025-02-28 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0027_outerentryconfig_building'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestiontype',
            name='has_score',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyquestiontype',
            name='prevents_visit_if_score_lte',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestiontype',
            name='score_depends_on',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_depends_on_question_type', to='survey.surveyquestiontype'),
        ),
        migrations.AddField(
            model_name='surveyquestiontype',
            name='score_max',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestiontype',
            name='score_min',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
