# Generated by Django 4.1.4 on 2025-03-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0028_surveyquestiontype_has_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='category',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
