# Generated by Django 4.1.4 on 2025-05-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0029_survey_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_mandatory_city',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
