# Generated by Django 4.1.4 on 2025-07-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0030_survey_is_mandatory_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(default='')),
                ('score_begin', models.IntegerField()),
                ('score_end', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
