# Generated by Django 4.1.4 on 2026-10-01 17:09

from django.db import migrations, models
from django.utils import timezone


def expire_legacy_challenges(apps, schema_editor):
    challenge = apps.get_model('survey', 'FillOutPhoneVerification')
    challenge.objects.filter(consumed_at__isnull=True).update(
        consumed_at=timezone.now(), code='', verification_token='')


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0031_surveyrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='filloutphoneverification',
            name='consumed_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='filloutphoneverification',
            name='failed_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='filloutphoneverification',
            name='code',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.RunPython(expire_legacy_challenges, migrations.RunPython.noop),
    ]
