# Generated by Django 5.2.4 on 2025-07-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=30, unique=True)),
                ('type', models.CharField(default='SMS', max_length=10)),
                ('view', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('path', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('to', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('msg_template', models.TextField()),
                ('url_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
