# Generated by Django 4.1.4 on 2026-10-01 23:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0042_client_wallet_balance_grant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InAppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=100)),
                ('kind', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=240)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.project')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_app_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='inappnotification',
            index=models.Index(fields=['recipient', 'project', '-created_at'], name='notif_personal_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='inappnotification',
            constraint=models.UniqueConstraint(fields=('recipient', 'project', 'source_key'), name='unique_personal_notification_event'),
        ),
    ]
