# Generated by Django 4.1.4 on 2023-02-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalali_date', models.CharField(max_length=12)),
                ('miladi_datetime', models.DateTimeField()),
                ('miladi_date', models.DateField(blank=True, default=None, null=True)),
                ('miladi_year', models.IntegerField(blank=True, default=None, null=True)),
                ('miladi_month', models.IntegerField(blank=True, default=None, null=True)),
                ('miladi_day', models.IntegerField(blank=True, default=None, null=True)),
                ('jalali_year', models.IntegerField(blank=True, default=None, null=True)),
                ('jalali_month', models.IntegerField(blank=True, default=None, null=True)),
                ('jalali_day', models.IntegerField(blank=True, default=None, null=True)),
                ('jalali_month_name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('miladi_month_name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('jalali_season_name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('miladi_season_name', models.CharField(blank=True, default=None, max_length=16, null=True)),
                ('jalali_year_quarter', models.IntegerField(blank=True, default=None, null=True)),
                ('miladi_year_quarter', models.IntegerField(blank=True, default=None, null=True)),
                ('miladi_day_of_the_week', models.IntegerField(blank=True, default=None, null=True)),
                ('jalali_day_of_the_week', models.IntegerField(blank=True, default=None, null=True)),
                ('miladi_week_no', models.IntegerField(blank=True, default=None, null=True)),
                ('jalali_week_no', models.IntegerField(blank=True, default=None, null=True)),
                ('custom_week_no', models.IntegerField(blank=True, default=None, null=True)),
                ('miladi_day_name', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('jalali_day_name', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=12)),
                ('boardlable', models.CharField(default=None, max_length=150, null=True)),
                ('store_name', models.CharField(default=None, max_length=120, null=True)),
                ('province', models.CharField(default=None, max_length=60, null=True)),
                ('city', models.CharField(default=None, max_length=60, null=True)),
            ],
        ),
    ]
