# Generated by Django 4.1.4 on 2023-02-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0033_alter_question_type'),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcensus',
            name='cencus',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visit.census'),
        ),
    ]
