# Generated by Django 4.1.4 on 2023-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_reportcensus_cencus'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('datetime', models.DateTimeField(blank=True, default=None, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('number', models.BigIntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
