# Generated by Django 4.1.4 on 2023-04-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_datematch'),
    ]

    operations = [
        migrations.AddField(
            model_name='dateconvert',
            name='project_week_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
