# Generated by Django 4.1.4 on 2024-02-28 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('limited_create_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_day', models.IntegerField(blank=True, default=90, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_length', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)])),
                ('min_length', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(1)])),
                ('extera_back_half_allowed', models.BooleanField(blank=True, default=True)),
                ('back_half_allowed', models.BooleanField(blank=True, default=True)),
                ('lower_case_characters', models.BooleanField(blank=True, default=True)),
                ('number_characters', models.BooleanField(blank=True, default=True)),
                ('upper_case_characters', models.BooleanField(blank=True, default=True)),
                ('other_characters', models.BooleanField(blank=True, default=True)),
                ('eternal_allowed', models.BooleanField(blank=True, default=False)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('has_advertise_plan', models.BooleanField(blank=True, default=False)),
                ('has_sms_plan', models.BooleanField(blank=True, default=False)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_change', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_utility.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.TextField(max_length=255, unique=True)),
                ('url', models.TextField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('is_eternal', models.BooleanField(blank=True, default=False)),
                ('back_half', models.TextField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(blank=True, default=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('datetime_last_change', models.DateTimeField(auto_now=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('domain', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='url_utility.userplan')),
            ],
        ),
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('short_url', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='url_utility.shorturl')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='url_utility.userplan')),
            ],
        ),
    ]
