# Generated by Django 4.1.4 on 2024-02-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_utility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clicklog',
            old_name='user',
            new_name='user_plan',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='user',
            new_name='user_plan',
        ),
    ]
