# Generated by Django 4.1.4 on 2024-05-13 08:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_utility', '0002_rename_user_clicklog_user_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='duration_day',
            field=models.IntegerField(blank=True, default=90, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
